---
- name: Install GUI group (Server with GUI)
  ansible.builtin.dnf:
    name: "{{ vnc_gui_group }}"
    state: present
  when: vnc_install_gui | bool

- name: Install TigerVNC server packages
  ansible.builtin.dnf:
    name: "{{ vnc_install_packages }}"
    state: present
